=== lancra/dotfiles/.config/snippets/snippet.schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$id": "https://raw.githubusercontent.com/lancra/dotfiles/main/.config/snippets/snippet.schema.json",
  "title": "Code Snippet",
  "description": "Configuration of a code snippet.",
  "type": "object",
  "properties": {
    "prefix": {
      "description": "The prefix(es) to use when selecting the snippet using Intellisense.",
      "oneOf": [
        {
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        {
          "type": "string"
        }
      ],
      "default": ""
    },
    "title": {
      "description": "The human readable name for the snippet.",
      "type": "string",
      "default": ""
    },
    "description": {
      "description": "The description provided more context around the purpose and usage of the snippet.",
      "type": "string",
      "default": ""
    },
    "scope": {
      "description": "The language name(s) to which this snippet applies.",
      "oneOf": [
        {
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        {
          "type": "string"
        }
      ],
      "default": ""
    },
    "body": {
      "description": "The content of the snippet.\n* Use $1 or ${1:defaultText} to define cursor positions.\n* Use $0 for the final cursor position.\n* Insert variable values with ${varName} and ${varName:defaultText}.\nReference: https://aka.ms/snippets",
      "oneOf": [
        {
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        {
          "type": "string"
        }
      ],
      "default": ""
    },
    "placeholders": {
      "description": "The metadata for placeholders defined in the body.",
      "type": "object",
      "additionalProperties": {
        "description": "The metadata for the placeholder with the defined position.",
        "type": "object",
        "properties": {
          "variable": {
            "description": "The variable name that represents the placeholder.",
            "type": "string",
            "default": ""
          },
          "tooltip": {
            "description": "The tooltip shown when entering the value.",
            "type": "string",
            "default": ""
          }
        },
        "required": ["variable", "tooltip"]
      }
    }
  },
  "required": ["title", "description", "scope", "body"]
}

=== lancra/dotfiles/.config/snippets/csharp/factm.snippet.json
{
  "title": "Fact Method Class",
  "description": "The shell class for unit testing a method.",
  "scope": "csharp",
  "body": [
    "public class The${1:Method}Method : $TM_FILENAME_BASE",
    "{",
    "    $0",
    "}"
  ],
  "placeholders": {
    "1": {
      "variable": "method",
      "tooltip": "The method being tested by the fact(s)."
    }
  }
}

=== lancra/dotfiles/.config/snippets/xml/msbuild/resxt.snippet.json
{
  "title": "Resources File Template",
  "description": "Provides the base template for a resx resources file.",
  "scope": "xml",
  "body": [
    "<?xml version=\"1.0\" encoding=\"utf-8\"?>",
    "<root>",
    "  <xsd:schema id=\"root\" xmlns=\"\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\" xmlns:msdata=\"urn:schemas-microsoft-com:xml-msdata\">",
    "    <xsd:import namespace=\"http://www.w3.org/XML/1998/namespace\" />",
    "    <xsd:element name=\"root\" msdata:IsDataSet=\"true\">",
    "      <xsd:complexType>",
    "        <xsd:choice maxOccurs=\"unbounded\">",
    "          <xsd:element name=\"metadata\">",
    "            <xsd:complexType>",
    "              <xsd:sequence>",
    "                <xsd:element name=\"value\" type=\"xsd:string\" minOccurs=\"0\" />",
    "              </xsd:sequence>",
    "              <xsd:attribute name=\"name\" use=\"required\" type=\"xsd:string\" />",
    "              <xsd:attribute name=\"type\" type=\"xsd:string\" />",
    "              <xsd:attribute name=\"mimetype\" type=\"xsd:string\" />",
    "              <xsd:attribute ref=\"xml:space\" />",
    "            </xsd:complexType>",
    "          </xsd:element>",
    "          <xsd:element name=\"assembly\">",
    "            <xsd:complexType>",
    "              <xsd:attribute name=\"alias\" type=\"xsd:string\" />",
    "              <xsd:attribute name=\"name\" type=\"xsd:string\" />",
    "            </xsd:complexType>",
    "          </xsd:element>",
    "          <xsd:element name=\"data\">",
    "            <xsd:complexType>",
    "              <xsd:sequence>",
    "                <xsd:element name=\"value\" type=\"xsd:string\" minOccurs=\"0\" msdata:Ordinal=\"1\" />",
    "                <xsd:element name=\"comment\" type=\"xsd:string\" minOccurs=\"0\" msdata:Ordinal=\"2\" />",
    "              </xsd:sequence>",
    "              <xsd:attribute name=\"name\" type=\"xsd:string\" use=\"required\" msdata:Ordinal=\"1\" />",
    "              <xsd:attribute name=\"type\" type=\"xsd:string\" msdata:Ordinal=\"3\" />",
    "              <xsd:attribute name=\"mimetype\" type=\"xsd:string\" msdata:Ordinal=\"4\" />",
    "              <xsd:attribute ref=\"xml:space\" />",
    "            </xsd:complexType>",
    "          </xsd:element>",
    "          <xsd:element name=\"resheader\">",
    "            <xsd:complexType>",
    "              <xsd:sequence>",
    "                <xsd:element name=\"value\" type=\"xsd:string\" minOccurs=\"0\" msdata:Ordinal=\"1\" />",
    "              </xsd:sequence>",
    "              <xsd:attribute name=\"name\" type=\"xsd:string\" use=\"required\" />",
    "            </xsd:complexType>",
    "          </xsd:element>",
    "        </xsd:choice>",
    "      </xsd:complexType>",
    "    </xsd:element>",
    "  </xsd:schema>",
    "  <resheader name=\"resmimetype\">",
    "    <value>text/microsoft-resx</value>",
    "  </resheader>",
    "  <resheader name=\"version\">",
    "    <value>2.0</value>",
    "  </resheader>",
    "  <resheader name=\"reader\">",
    "    <value>System.Resources.ResXResourceReader, System.Windows.Forms, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089</value>",
    "  </resheader>",
    "  <resheader name=\"writer\">",
    "    <value>System.Resources.ResXResourceWriter, System.Windows.Forms, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089</value>",
    "  </resheader>",
    "  $0",
    "</root>",
    ""
  ]
}

=== lancra/dotfiles/.config/snippets/csharp/rettaskdoc.snippet.json
{
  "title": "Returned Task Documentation",
  "description": "The XML documentation for a returned asynchronous Task.",
  "scope": "csharp",
  "body": [
    "/// <returns>",
    "/// The <see cref=\"Task\"/> that represents the asynchronous operation,",
    "/// containing the $0",
    "/// </returns>"
  ]
}

=== lancra/dotfiles/.config/snippets/sql/database/dropdb.snippet.json
{
  "title": "Drop Database",
  "description": "Drops a database, preventing other connections from blocking the operation.",
  "scope": "sql",
  "body": [
    "USE master",
    "ALTER DATABASE ${1:database}",
    "    SET SINGLE_USER WITH ROLLBACK IMMEDIATE",
    "",
    "DROP DATABASE $1",
    "$0"
  ]
}

=== lancra/dotfiles/.config/snippets/csharp/factcd.snippet.json
{
  "title": "Fact Class with Data",
  "description": "The shell class for unit testing with seed data.",
  "scope": "csharp",
  "body": [
    "public class $TM_FILENAME_BASE : IDisposable",
    "{",
    "    private readonly AutoMocker _mocker = new();",
    "    private readonly SeedDataFixture _seedDataFixture = new();",
    "",
    "    public $TM_FILENAME_BASE()",
    "        => _mocker.Use(_seedDataFixture.NewDbContext);",
    "",
    "    public void Dispose()",
    "    {",
    "        Dispose(true);",
    "        GC.SuppressFinalize(this);",
    "    }",
    "",
    "    protected virtual void Dispose(bool disposing)",
    "    {",
    "        if (disposing)",
    "        {",
    "            _seedDataFixture.Dispose();",
    "        }",
    "    }",
    "",
    "    private ${1:SystemUnderTest} CreateSystemUnderTest()",
    "        => _mocker.CreateInstance<$1>();",
    "",
    "    public class The${2:Method}Method : $TM_FILENAME_BASE",
    "    {",
    "        $0",
    "    }",
    "}"
  ],
  "placeholders": {
    "1": {
      "variable": "systemUnderTest",
      "tooltip": "The system being tested by the fact(s)."
    },
    "2": {
      "variable": "method",
      "tooltip": "The method being tested by the fact(s)."
    }
  }
}

=== lancra/dotfiles/.config/snippets/assertex.snippet.json
{
  "title": "Assert Exception",
  "description": "Creates an xUnit assertion to verify that an exception is not null and is a particular type.",
  "scope": "csharp",
  "body": [
    "Assert.NotNull(exception);",
    "Assert.IsType<${1:Exception}>(exception);"
  ],
  "placeholders": {
    "1": {
      "variable": "exceptionType",
      "tooltip": "The expected exception type."
    }
  }
}

=== lancra/dotfiles/.config/snippets/csharp/factp.snippet.json
{
  "title": "Fact Property Class",
  "description": "The shell class for unit testing a property.",
  "scope": "csharp",
  "body": [
    "public class The${1:Property}Property : $TM_FILENAME_BASE",
    "{",
    "    $0",
    "}"
  ],
  "placeholders": {
    "1": {
      "variable": "property",
      "tooltip": "The property being tested by the fact(s)."
    }
  }
}

=== lancra/dotfiles/.config/snippets/xml/msbuild/intvisg.snippet.json
{
  "title": "Internals Visible To Item Group",
  "description": "The MSBuild item group used to expose project internals to another project.",
  "scope": "xml",
  "body": [
    "<ItemGroup>",
    "  <InternalsVisibleTo Include=\"DynamicProxyGenAssembly2\" />",
    "  <InternalsVisibleTo Include=\"${1:Project}\" />",
    "</ItemGroup>$0"
  ],
  "placeholders": {
    "1": {
      "variable": "project",
      "tooltip": "The project to expose internals to."
    }
  }
}
