=== lancra/dotfiles/.config/snippets/snippet.schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$id": "https://raw.githubusercontent.com/lancra/dotfiles/main/.config/snippets/snippet.schema.json",
  "title": "Code Snippet",
  "description": "Configuration of a code snippet.",
  "type": "object",
  "properties": {
    "prefix": {
      "description": "The prefix(es) to use when selecting the snippet using Intellisense.",
      "oneOf": [
        {
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        {
          "type": "string"
        }
      ],
      "default": ""
    },
    "title": {
      "description": "The human readable name for the snippet.",
      "type": "string",
      "default": ""
    },
    "description": {
      "description": "The description provided more context around the purpose and usage of the snippet.",
      "type": "string",
      "default": ""
    },
    "scope": {
      "description": "The language name(s) to which this snippet applies.",
      "oneOf": [
        {
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        {
          "type": "string"
        }
      ],
      "default": ""
    },
    "body": {
      "description": "The content of the snippet.\n* Use $1 or ${1:defaultText} to define cursor positions.\n* Use $0 for the final cursor position.\n* Insert variable values with ${varName} and ${varName:defaultText}.\nReference: https://aka.ms/snippets",
      "oneOf": [
        {
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        {
          "type": "string"
        }
      ],
      "default": ""
    },
    "placeholders": {
      "description": "The metadata for placeholders defined in the body.",
      "type": "object",
      "additionalProperties": {
        "description": "The metadata for the placeholder with the defined position.",
        "type": "object",
        "properties": {
          "variable": {
            "description": "The variable name that represents the placeholder.",
            "type": "string",
            "default": ""
          },
          "tooltip": {
            "description": "The tooltip shown when entering the value.",
            "type": "string",
            "default": ""
          }
        },
        "required": ["variable", "tooltip"]
      }
    }
  },
  "required": ["title", "description", "scope", "body"]
}

=== lancra/dotfiles/.config/snippets/aaa.snippet.json
{
  "prefix": "aaa",
  "title": "Arrange Act Assert",
  "description": "Comments for the arrange-act-assert test structural pattern.",
  "scope": ["csharp", "rust"],
  "body": [
    "$LINE_COMMENT Arrange",
    "$0",
    "",
    "$LINE_COMMENT Act",
    "",
    "",
    "$LINE_COMMENT Assert",
    ""
  ]
}

=== lancra/dotfiles/.config/snippets/xml/msbuild/intvis.snippet.json
{
  "title": "Internals Visible To Item",
  "description": "The MSBuild item used to expose project internals to another project.",
  "scope": "xml",
  "body": "<InternalsVisibleTo Include=\"${1:Project}\" />$0",
  "placeholders": {
    "1": {
      "variable": "project",
      "tooltip": "The project to expose internals to."
    }
  }
}

=== lancra/dotfiles/.config/snippets/csharp/factc.snippet.json
{
  "title": "Fact Class",
  "description": "The shell class for unit testing.",
  "scope": "csharp",
  "body": [
    "public class $TM_FILENAME_BASE",
    "{",
    "    private readonly AutoMocker _mocker = new();",
    "",
    "    private ${1:SystemUnderTest} CreateSystemUnderTest()",
    "        => _mocker.CreateInstance<$1>();",
    "",
    "    public class The${2:Method}Method : $TM_FILENAME_BASE",
    "    {",
    "        $0",
    "    }",
    "}"
  ],
  "placeholders": {
    "1": {
      "variable": "systemUnderTest",
      "tooltip": "The system being tested by the fact(s)."
    },
    "2": {
      "variable": "method",
      "tooltip": "The method being tested by the fact(s)."
    }
  }
}

=== lancra/dotfiles/.config/snippets/xml/msbuild/resxe.snippet.json
{
  "title": "Resources File Element",
  "description": "Provides an element for a resx resources file.",
  "scope": "xml",
  "body": [
    "<data name=\"${1:Name}\" xml:space=\"preserve\">",
    "  <value>${2:Value}</value>",
    "</data>$0"
  ],
  "placeholders": {
    "1": {
      "variable": "name",
      "tooltip": "The name of the resource."
    },
    "2": {
      "variable": "value",
      "tooltip": "The value of the resource."
    }
  }
}

=== lancra/dotfiles/.config/snippets/csharp/rpropi.snippet.json
{
  "title": "Required Init-Only Property",
  "description": "An automatically implemented, required property with a get accessor and init-only set accessor.",
  "scope": "csharp",
  "body": "public required ${1:int} ${2:MyProperty} { get; init; }$0",
  "placeholders": {
    "1": {
      "variable": "type",
      "tooltip": "The property type."
    },
    "2": {
      "variable": "name",
      "tooltip": "The property name."
    }
  }
}

=== lancra/dotfiles/.config/snippets/csharp/rettaskdocw.snippet.json
{
  "title": "Wrapped Returned Task Documentation",
  "description": "The wrapped XML documentation for a returned asynchronous Task.",
  "scope": "csharp",
  "body": [
    "/// <returns>",
    "/// The <see cref=\"Task\"/> that represents the asynchronous operation, containing the $0",
    "/// </returns>"
  ]
}

=== lancra/dotfiles/.config/snippets/csharp/sdfd.snippet.json
{
  "title": "Seed Data Fixture Disposal",
  "description": "The disposal methods for a seed data fixture.",
  "scope": "csharp",
  "body": [
    "public void Dispose()",
    "{",
    "    Dispose(true);",
    "    GC.SuppressFinalize(this);",
    "}",
    "",
    "protected virtual void Dispose(bool disposing)",
    "{",
    "    if (disposing)",
    "    {",
    "        _seedDataFixture.Dispose();",
    "    }",
    "}$0"
  ]
}

=== lancra/dotfiles/.config/snippets/cancdoc.snippet.json
{
  "title": "Cancellation Token Documentation",
  "description": "The XML documentation for a cancellation token parameter.",
  "scope": "csharp",
  "body": [
    "/// <param name=\"cancellationToken\">",
    "/// A <see cref=\"CancellationToken\"/> to observe while waiting for the task to complete.",
    "/// </param>$0"
  ]
}
